-- MySQL Script generated by MySQL Workbench
-- 01/18/16 15:07:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema infotutor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema infotutor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `infotutor` DEFAULT CHARACTER SET latin1 ;
USE `infotutor` ;

-- -----------------------------------------------------
-- Table `infotutor`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotutor`.`curso` (
  `Sigla` VARCHAR(6) NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  `NivelCurso` INT(11) NOT NULL,
  PRIMARY KEY (`Sigla`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infotutor`.`Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotutor`.`Matricula` (
  `siglaCursoM` VARCHAR(6) NOT NULL,
  `idUsuario` INT(11) NOT NULL,
  PRIMARY KEY (`siglaCursoM`, `idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infotutor`.`tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotutor`.`tema` (
  `siglaCursoT` VARCHAR(6) NOT NULL,
  `IdTema` INT(11) NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`siglaCursoT`, `IdTema`),
  CONSTRAINT `Sigla`
    FOREIGN KEY (`siglaCursoT`)
    REFERENCES `infotutor`.`curso` (`Sigla`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infotutor`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotutor`.`usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NULL,
  `Apellidos` VARCHAR(100) NULL DEFAULT NULL,
  `Correo` VARCHAR(50) NULL DEFAULT NULL,
  `Usuario` VARCHAR(20) NULL DEFAULT NULL,
  `Contrasena` VARCHAR(20) NULL DEFAULT NULL,
  `Tipo` VARCHAR(20) NULL DEFAULT NULL,
  `Nivel` INT(11) NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `Usuario` (`Usuario` ASC),
  UNIQUE INDEX `Contrasena_UNIQUE` (`Contrasena` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infotutor`.`foro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotutor`.`foro` (
  `IdForo` INT(11) NOT NULL AUTO_INCREMENT,
  `IdTema` INT(11) NOT NULL,
  `FechaCreacion` INT(11) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `EnunciadoForo` VARCHAR(500) NOT NULL,
  `IdUsuario` INT NOT NULL,
  PRIMARY KEY (`IdForo`, `IdTema`),
  INDEX `IdTema` (`IdTema` ASC),
  INDEX `idUsuario_idx` (`IdUsuario` ASC),
  CONSTRAINT `foro_ibfk_1`
    FOREIGN KEY (`IdTema`)
    REFERENCES `infotutor`.`tema` (`IdTema`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `infotutor`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infotutor`.`practica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotutor`.`practica` (
  `IdPractica` INT(11) NOT NULL AUTO_INCREMENT,
  `RespuestasCorrectas` INT(11) NOT NULL,
  `RespuestasIncorrectas` INT(11) NOT NULL,
  PRIMARY KEY (`IdPractica`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infotutor`.`practicausuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotutor`.`practicausuario` (
  `IdPractica` INT(11) NOT NULL,
  `IdUsuario` INT(11) NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`IdPractica`, `IdUsuario`),
  UNIQUE INDEX `IdPractica` (`IdPractica` ASC, `IdUsuario` ASC),
  INDEX `IdUsuario` (`IdUsuario` ASC),
  CONSTRAINT `practicausuario_ibfk_1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `infotutor`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `practicausuario_ibfk_2`
    FOREIGN KEY (`IdPractica`)
    REFERENCES `infotutor`.`practica` (`IdPractica`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infotutor`.`pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotutor`.`pregunta` (
  `IdPregunta` INT(11) NOT NULL AUTO_INCREMENT,
  `IdTema` INT(11) NOT NULL,
  `Enunciado` VARCHAR(500) NOT NULL,
  `Respuesta` VARCHAR(500) NOT NULL,
  `Valor` INT(11) NOT NULL,
  `Tipo` INT(11) NOT NULL,
  PRIMARY KEY (`IdPregunta`, `IdTema`),
  INDEX `IdTema` (`IdTema` ASC),
  UNIQUE INDEX `Enunciado_UNIQUE` (`Enunciado` ASC),
  CONSTRAINT `pregunta_ibfk_1`
    FOREIGN KEY (`IdTema`)
    REFERENCES `infotutor`.`tema` (`IdTema`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infotutor`.`preguntascuestionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotutor`.`preguntascuestionario` (
  `IdCuestionario` INT(11) NOT NULL,
  `IdPregunta` INT(11) NOT NULL,
  INDEX `IdPregunta` (`IdPregunta` ASC),
  PRIMARY KEY (`IdCuestionario`, `IdPregunta`),
  CONSTRAINT `preguntascuestionario_ibfk_2`
    FOREIGN KEY (`IdPregunta`)
    REFERENCES `infotutor`.`pregunta` (`IdPregunta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infotutor`.`preguntasusuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotutor`.`preguntasusuario` (
  `IdPreguntaUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `IdUsuario` INT(11) NOT NULL,
  `IdTema` INT(11) NOT NULL,
  `Contenido` VARCHAR(500) NOT NULL,
  `Respuestas` VARCHAR(10000) NOT NULL,
  `Tipo` VARCHAR(100) NOT NULL,
  `Estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`IdPreguntaUsuario`, `IdUsuario`, `IdTema`),
  INDEX `IdTema` (`IdTema` ASC),
  INDEX `IdUsuario` (`IdUsuario` ASC),
  CONSTRAINT `preguntasusuario_ibfk_1`
    FOREIGN KEY (`IdTema`)
    REFERENCES `infotutor`.`tema` (`IdTema`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `preguntasusuario_ibfk_2`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `infotutor`.`Matricula` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infotutor`.`prueba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotutor`.`prueba` (
  `IdPrueba` INT(11) NOT NULL AUTO_INCREMENT,
  `Calificacion` DECIMAL(4) NOT NULL,
  `PuntosTotales` INT(11) NOT NULL,
  `PuntosObtenidos` INT(11) NOT NULL,
  `RespuestasCorrectas` INT(11) NOT NULL,
  `RespuestasIncorrectas` INT(11) NOT NULL,
  PRIMARY KEY (`IdPrueba`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infotutor`.`pruebausuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotutor`.`pruebausuario` (
  `IdPrueba` INT(11) NOT NULL,
  `IdUsuario` INT(11) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  PRIMARY KEY (`IdPrueba`, `IdUsuario`),
  UNIQUE INDEX `IdPrueba` (`IdPrueba` ASC, `IdUsuario` ASC),
  INDEX `IdUsuario` (`IdUsuario` ASC),
  CONSTRAINT `pruebausuario_ibfk_1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `infotutor`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pruebausuario_ibfk_2`
    FOREIGN KEY (`IdPrueba`)
    REFERENCES `infotutor`.`prueba` (`IdPrueba`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infotutor`.`recomendacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotutor`.`recomendacion` (
  `IdRecomendacion` INT(11) NOT NULL,
  `IdPrueba` INT(11) NOT NULL,
  `Descripcion` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`IdRecomendacion`, `IdPrueba`),
  CONSTRAINT `recomendacion_ibfk_1`
    FOREIGN KEY (`IdPrueba`)
    REFERENCES `infotutor`.`prueba` (`IdPrueba`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infotutor`.`respuestaforo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotutor`.`respuestaforo` (
  `IdRespuestaForo` INT(11) NOT NULL AUTO_INCREMENT,
  `IdForo` INT(11) NOT NULL,
  `Respuesta` VARCHAR(500) NOT NULL,
  `Calificacion` INT(11) NOT NULL,
  `IdUsuario` INT NOT NULL,
  PRIMARY KEY (`IdRespuestaForo`),
  INDEX `IdForo_idx` (`IdForo` ASC),
  INDEX `idUsuario_idx` (`IdUsuario` ASC),
  CONSTRAINT `IdForo`
    FOREIGN KEY (`IdForo`)
    REFERENCES `infotutor`.`foro` (`IdForo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `infotutor`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infotutor`.`respuestaincorrecta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotutor`.`respuestaincorrecta` (
  `IdRespuestaIncorrecta` INT(11) NOT NULL AUTO_INCREMENT,
  `IdPregunta` INT(11) NOT NULL,
  `Respuesta` VARCHAR(500) NOT NULL,
  `IdCuestionario` INT NOT NULL,
  PRIMARY KEY (`IdRespuestaIncorrecta`, `IdPregunta`, `IdCuestionario`),
  INDEX `IdCuestionario_idx` (`IdCuestionario` ASC),
  CONSTRAINT `IdPregunta`
    FOREIGN KEY (`IdPregunta`)
    REFERENCES `infotutor`.`preguntascuestionario` (`IdPregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdCuestionario`
    FOREIGN KEY (`IdCuestionario`)
    REFERENCES `infotutor`.`preguntascuestionario` (`IdCuestionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `infotutor`.`Contenido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `infotutor`.`Contenido` (
  `IdContenido` INT NOT NULL AUTO_INCREMENT,
  `IdTemaC` INT NOT NULL,
  `ContenidoT` VARCHAR(45) NULL,
  PRIMARY KEY (`IdContenido`, `IdTemaC`),
  INDEX `IdTemaC_idx` (`IdTemaC` ASC),
  CONSTRAINT `IdTemaC`
    FOREIGN KEY (`IdTemaC`)
    REFERENCES `infotutor`.`tema` (`IdTema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
